server:
  port: 8083

spring:
  application:
    name: compras-service
  datasource:
    url: jdbc:h2:mem:comprasdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
